#testing1
name: 'Terraform Automation'

on:
  push:
    branches:
      - dev
      - qa
      - prod   

jobs:
  terraform:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    name: 'Terraform-dev'
    runs-on: ubuntu-latest
    
    #environment: dev  

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
  
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init
      
      # Validates the configuration used in the GitHub Action workflow
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Generates an execution plan for Terraform, on push
      - name: Terraform Plan
        id: plan
        #if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        #if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve

  terraform2:
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    name: 'Terraform-qa'
    runs-on: ubuntu-latest
    
    #environment: dev  

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
  
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init
      
      # Validates the configuration used in the GitHub Action workflow
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Generates an execution plan for Terraform, on push
      - name: Terraform Plan
        id: plan
        #if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        #if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
        run: terraform apply -auto-approve


  terraform3:
    if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
    name: 'Terraform-prod'
    runs-on: ubuntu-latest
    
    #environment: dev  

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
  
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init
      
      # Validates the configuration used in the GitHub Action workflow
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Generates an execution plan for Terraform, on push
      - name: Terraform Plan
        id: plan
        #if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        #if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
        run: terraform apply -auto-approve




