#testing
name: 'Terraform Automation'

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  terraform:
    name: 'Terraform-dev'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: if dev, terraform init, validate, plan, apply
        id: init
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform init
        env:
          TF_WORKSPACE: "dev" 
          
      - name: Terraform workspace
        id: workspace
        run: terraform workspace select ppb-dev
          
      - name: validate
        run: |
          terraform validate -no-color
          terraform plan -no-color
          terraform apply -auto-approve
        env:
          TYRELL_ENVIRONMENT: dev
          
     
          



